// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: rxzzhxqevbesewusibdm

class SupabaseConfig {
  static const String supabaseUrl = 'https://rxzzhxqevbesewusibdm.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4enpoeHFldmJlc2V3dXNpYmRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIxMTI4MDUsImV4cCI6MjA3NzY4ODgwNX0.u58x_OEPVpRDJzHkbp1GHMgTkbiYHgHXkIifKyKRKm4';
}
